version: '3.9'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
  postgres:
    image: postgres:14.3-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=ton_db
      - POSTGRES_USER=ton_wladek
      - POSTGRES_PASSWORD=approved_by_ton
